name: Maven Package

on:
  release:
    types: [published]
    
env:
  version: ${{ github.event.release.tag_name }}

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK 8
      uses: actions/setup-java@v2
      with:
        java-version: '8.0'
        distribution:  'adopt'
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml

    - name: Publish to GitHub Packages Apache Maven
      run: mvn deploy -DskipTests=true -DmyShuttleVersion=${{github.event.release.tag_name}} --batch-mode --no-transfer-progress
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
